"""Initial migration

Revision ID: 4e67d4bca4e5
Revises: 
Create Date: 2025-01-19 03:02:37.635887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e67d4bca4e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('flight_date', sa.DateTime(), nullable=True),
    sa.Column('flight_status', sa.String(length=20), nullable=True),
    sa.Column('departure_airport', sa.String(length=50), nullable=True),
    sa.Column('departure_timezone', sa.String(length=50), nullable=True),
    sa.Column('departure_iata', sa.String(length=10), nullable=True),
    sa.Column('departure_delay', sa.Float(), nullable=True),
    sa.Column('departure_scheduled', sa.DateTime(), nullable=True),
    sa.Column('departure_actual', sa.DateTime(), nullable=True),
    sa.Column('arrival_airport', sa.String(length=50), nullable=True),
    sa.Column('arrival_timezone', sa.String(length=50), nullable=True),
    sa.Column('arrival_iata', sa.String(length=10), nullable=True),
    sa.Column('arrival_scheduled', sa.DateTime(), nullable=True),
    sa.Column('arrival_actual', sa.DateTime(), nullable=True),
    sa.Column('airline_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_number'], ['flights.flight_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    op.drop_table('flights')
    # ### end Alembic commands ###
